export default {
  questions: [
    {
      name: "Two Sum",
      url: "https://leetcode.com/problems/two-sum/",
      type: "array",
      difficulty: "easy",
    },
    {
      name: "Best Time to Buy and Sell Stock",
      url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
      type: "array",
      difficulty: "easy",
    },
    {
      name: "Contains Duplicate",
      url: "https://leetcode.com/problems/contains-duplicate/",
      type: "array",
      difficulty: "easy",
    },
    {
      name: "Product of Array Except Self",
      url: "https://leetcode.com/problems/product-of-array-except-self/",
      type: "array",
      difficulty: "medium",
    },
    {
      name: "Maximum Subarray",
      url: "https://leetcode.com/problems/maximum-subarray/",
      type: "array",
      difficulty: "easy",
    },
    {
      name: "Maximum Product Subarray",
      url: "https://leetcode.com/problems/maximum-product-subarray/",
      type: "array",
      difficulty: "medium",
    },
    {
      name: " Find Minimum in Rotated Sorted Array",
      url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
      type: "array",
      difficulty: "medium",
    },
    {
      name: "Search in Rotated Sorted Array",
      url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
      type: "array",
      difficulty: "medium",
    },
    {
      name: "3Sum",
      url: "https://leetcode.com/problems/3sum/",
      type: "array",
      difficulty: "medium",
    },
    {
      name: "Container With Most Water",
      url: "https://leetcode.com/problems/container-with-most-water/",
      type: "array",
      difficulty: "medium",
    },
    {
      name: "Sum of Two Integers",
      url: "https://leetcode.com/problems/sum-of-two-integers/",
      type: "binary",
      difficulty: "medium",
    },
    {
      name: "Number of 1 Bits",
      url: "https://leetcode.com/problems/number-of-1-bits/",
      type: "binary",
      difficulty: "easy",
    },
    {
      name: "Counting Bits",
      url: "https://leetcode.com/problems/counting-bits/",
      type: "binary",
      difficulty: "easy",
    },
    {
      name: "Missing Number",
      url: "https://leetcode.com/problems/missing-number/",
      type: "binary",
      difficulty: "easy",
    },
    {
      name: "Reverse Bits",
      url: "https://leetcode.com/problems/reverse-bits/",
      type: "binary",
      difficulty: "easy",
    },
    {
      name: "Climbing Stairs",
      url: "https://leetcode.com/problems/climbing-stairs/",
      type: "dynamic-programming",
      difficulty: "easy",
    },
    {
      name: "Coin Change",
      url: "https://leetcode.com/problems/coin-change/",
      type: "dynamic-programming",
      difficulty: "medium",
    },
    {
      name: "Longest Increasing Subsequence",
      url: "https://leetcode.com/problems/longest-increasing-subsequence/",
      type: "dynamic-programming",
      difficulty: "medium",
    },
    {
      name: "Longest Common Subsequence",
      url: "https://leetcode.com/problems/longest-common-subsequence/",
      type: "dynamic-programming",
      difficulty: "easy",
    },
    {
      name: "Word Break Problem",
      url: "https://leetcode.com/problems/word-break/",
      type: "dynamic-programming",
      difficulty: "medium",
    },
    {
      name: "Combination Sum",
      url: "https://leetcode.com/problems/combination-sum-iv/",
      type: "dynamic-programming",
      difficulty: "medium",
    },
    {
      name: "House Robber",
      url: "https://leetcode.com/problems/house-robber/",
      type: "dynamic-programming",
      difficulty: "medium",
    },
    {
      name: "House Robber II",
      url: "https://leetcode.com/problems/house-robber-ii/",
      type: "dynamic-programming",
      difficulty: "medium",
    },
    {
      name: "Decode Ways",
      url: "https://leetcode.com/problems/decode-ways/",
      type: "dynamic-programming",
      difficulty: "medium",
    },
    {
      name: "Unique Paths",
      url: "https://leetcode.com/problems/unique-paths/",
      type: "dynamic-programming",
      difficulty: "medium",
    },
    {
      name: "Jump Game",
      url: "https://leetcode.com/problems/jump-game/",
      type: "dynamic-programming",
      difficulty: "medium",
    },
    {
      name: "Clone Graph",
      url: "https://leetcode.com/problems/clone-graph/",
      type: "graph",
      difficulty: "medium",
    },
    {
      name: "Course Schedule",
      url: "https://leetcode.com/problems/course-schedule/",
      type: "graph",
      difficulty: "medium",
    },
    {
      name: "Pacific Atlantic Water Flow",
      url: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
      type: "graph",
      difficulty: "medium",
    },
    {
      name: "Number of Islands",
      url: "https://leetcode.com/problems/number-of-islands/",
      type: "graph",
      difficulty: "medium",
    },
    {
      name: "Longest Consecutive Sequence",
      url: "https://leetcode.com/problems/longest-consecutive-sequence/",
      type: "graph",
      difficulty: "medium",
    },
    {
      name: "Insert Interval",
      url: "https://leetcode.com/problems/insert-interval/",
      type: "interval",
      difficulty: "medium",
    },
    {
      name: "Merge Intervals",
      url: "https://leetcode.com/problems/merge-intervals/",
      type: "interval",
      difficulty: "medium",
    },
    {
      name: "Non-overlapping Intervals",
      url: "https://leetcode.com/problems/non-overlapping-intervals/",
      type: "interval",
      difficulty: "medium",
    },

    {
      name: "Reverse a Linked List",
      url: "https://leetcode.com/problems/reverse-linked-list/",
      type: "linked-list",
      difficulty: "easy",
    },
    {
      name: "Detect Cycle in a Linked List",
      url: "https://leetcode.com/problems/linked-list-cycle/",
      type: "linked-list",
      difficulty: "easy",
    },
    {
      name: "Merge Two Sorted Lists",
      url: "https://leetcode.com/problems/merge-two-sorted-lists/",
      type: "linked-list",
      difficulty: "easy",
    },
    {
      name: "Merge K Sorted Lists",
      url: "https://leetcode.com/problems/merge-k-sorted-lists/",
      type: "linked-list",
      difficulty: "hard",
    },
    {
      name: "Remove Nth Node From End Of List",
      url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
      type: "linked-list",
      difficulty: "medium",
    },
    {
      name: "Reorder List",
      url: "https://leetcode.com/problems/reorder-list/",
      type: "linked-list",
      difficulty: "medium",
    },
    {
      name: "Set Matrix Zeroes",
      url: "https://leetcode.com/problems/set-matrix-zeroes/",
      type: "matrix",
      difficulty: "medium",
    },
    {
      name: "Spiral Matrix",
      url: "https://leetcode.com/problems/spiral-matrix/",
      type: "matrix",
      difficulty: "medium",
    },
    {
      name: "Rotate Image",
      url: "https://leetcode.com/problems/rotate-image/",
      type: "matrix",
      difficulty: "medium",
    },
    {
      name: "Word Search",
      url: "https://leetcode.com/problems/word-search/",
      type: "matrix",
      difficulty: "medium",
    },
    {
      name: "Longest Substring Without Repeating Characters",
      url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
      type: "string",
      difficulty: "medium",
    },
    {
      name: "Longest Repeating Character Replacement",
      url: "https://leetcode.com/problems/longest-repeating-character-replacement/",
      type: "string",
      difficulty: "medium",
    },
    {
      name: "Minimum Window Substring",
      url: "https://leetcode.com/problems/minimum-window-substring/",
      type: "string",
      difficulty: "hard",
    },
    {
      name: "Valid Anagram",
      url: "https://leet0code.com/problems/valid-anagram/",
      type: "string",
      difficulty: "easy",
    },
    {
      name: "Group Anagrams",
      url: "https://leetcode.com/problems/group-anagrams/",
      type: "string",
      difficulty: "medium",
    },
    {
      name: "Valid Parentheses",
      url: "https://leetcode.com/problems/valid-parentheses/",
      type: "string",
      difficulty: "easy",
    },
    {
      name: "Valid Palindrome",
      url: "https://leetcode.com/problems/valid-palindrome/",
      type: "string",
      difficulty: "easy",
    },
    {
      name: "Longest Palindromic Substring",
      url: "https://leetcode.com/problems/longest-palindromic-substring/",
      type: "string",
      difficulty: "medium",
    },
    {
      name: "Palindromic Substrings",
      url: "https://leetcode.com/problems/palindromic-substrings/",
      type: "string",
      difficulty: "medium",
    },
    {
      name: "Maximum Depth of Binary Tree",
      url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
      type: "tree",
      difficulty: "easy",
    },
    {
      name: "Same Tree",
      url: "https://leetcode.com/problems/same-tree/",
      type: "tree",
      difficulty: "easy",
    },
    {
      name: "Invert/Flip Binary Tree",
      url: "https://leetcode.com/problems/invert-binary-tree/",
      type: "tree",
      difficulty: "easy",
    },
    {
      name: "Binary Tree Maximum Path Sum",
      url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
      type: "tree",
      difficulty: "hard",
    },
    {
      name: "Binary Tree Level Order Traversal",
      url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
      type: "tree",
      difficulty: "medium",
    },
    {
      name: "Serialize and Deserialize Binary Tree",
      url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
      type: "tree",
      difficulty: "hard",
    },
    {
      name: "Subtree of Another Tree",
      url: "https://leetcode.com/problems/subtree-of-another-tree/",
      type: "tree",
      difficulty: "easy",
    },
    {
      name: "Construct Binary Tree from Preorder and Inorder Traversal",
      url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
      type: "tree",
      difficulty: "medium",
    },
    {
      name: "Validate Binary Search Tree",
      url: "https://leetcode.com/problems/validate-binary-search-tree/",
      type: "tree",
      difficulty: "medium",
    },
    {
      name: "Kth Smallest Element in a BST",
      url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
      type: "tree",
      difficulty: "medium",
    },
    {
      name: "Lowest Common Ancestor of BST",
      url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
      type: "tree",
      difficulty: "easy",
    },
    {
      name: "Implement Trie (Prefix Tree)",
      url: "https://leetcode.com/problems/implement-trie-prefix-tree/",
      type: "tree",
      difficulty: "medium",
    },
    {
      name: "Add and Search Word",
      url: "https://leetcode.com/problems/add-and-search-word-data-structure-design/",
      type: "tree",
      difficulty: "medium",
    },
    {
      name: "Word Search II",
      url: "https://leetcode.com/problems/word-search-ii/",
      type: "tree",
      difficulty: "hard",
    },
    {
      name: "Merge K Sorted Lists",
      url: "https://leetcode.com/problems/merge-k-sorted-lists/",
      type: "heap",
      difficulty: "hard",
    },
    {
      name: "Top K Frequent Elements",
      url: "https://leetcode.com/problems/top-k-frequent-elements/",
      type: "heap",
      difficulty: "medium",
    },
    {
      name: "Find Median from Data Stream",
      url: "https://leetcode.com/problems/find-median-from-data-stream/",
      type: "heap",
      difficulty: "hard",
    },
  ],
};
